"""Tests for Day 7."""

from solutions.day07 import part1, part2

# Paste the example input from the puzzle description here
EXAMPLE = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""


# def test_beam_split():
#    manifold = parse(EXAMPLE)



def test_part1():
    """Test part 1 with example input."""
    # Update expected value from puzzle description
    assert part1(EXAMPLE) == 21


def test_part2():
    """Test part 2 with example input."""
    assert part2(EXAMPLE) == 40

